const express = require('express')
const app = express()
require('dotenv').config()
const PORT = process.env.PORT
const bodyParser = require('body-parser')
const cookieParser = require('cookie-parser')
const dbConnect = require('./config/dbConnect')
const morgan = require('morgan')
const cors = require('cors')
const { errorHandler } = require('./middlewares/errorHandler')

const categoryRouter = require('./routes/categoryRoute')
const brandRouter = require('./routes/brandRoute')
const colorRouter = require('./routes/colorRoute')
const productRouter = require('./routes/productRoute')
const authRouter = require('./routes/authRoute')
const uploadRouter = require('./routes/uploadRoute')
const userRouter = require('./routes/userRoute')
const addressRouter = require('./routes/addressRoute')
const wishlistRouter = require('./routes/wishlistRoute')
const ratingRouter = require('./routes/ratingRoute')
const cartRouter = require('./routes/cartRoute')
const orderRouter = require('./routes/orderRoute')

dbConnect()

app.use(cors())
app.use(morgan('dev'))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(cookieParser())

app.use('/api/category', categoryRouter)
app.use('/api/brand', brandRouter)
app.use('/api/color', colorRouter)
app.use('/api/product', productRouter)
app.use('/api/auth', authRouter)
app.use('/api/upload', uploadRouter)
app.use('/api/user', userRouter)
app.use('/api/address', addressRouter)
app.use('/api/wishlist', wishlistRouter)
app.use('/api/rating', ratingRouter)
app.use('/api/cart', cartRouter)
app.use('/api/order', orderRouter)

app.use(errorHandler)

app.listen(PORT, () => {
    console.log(`Server is running at PORT ${PORT}`)
})